### ISSUE TITLE
EasyBuild dry run does not report errors in some cases

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/production#1304]
Becase dry run is called with all the eb_files as an argument, it does not work as expected in some cases. 
For example, consider files `recipe1.eb` and `recipe2.eb`. If `recipe2.eb` depends on `recipe1.eb`, doing:
`eb recipe1.eb recipe2.eb -Dr` will work fine, while `eb recipe2.eb -D` will not work fine if `recipe1.eb` is not contained in the robot paths.

**Comment by victorusu** [comment]
@teojgo, I believe that this is the expected behavior. 
But if you think that this is a bug, can you an issue on the [main EB repo](https://github.com/easybuilders/easybuild-framework)?
