### ISSUE TITLE
Configuring Hadoop fails with complains about "snappy" libraries

### ISSUE THREAD

**Issue by moravveji** [eth-cscs/production#1462]
Hi

I am trying to install Hadoop on Breniac. However, the configure step gives some critical warnings, specifically 

``` bash
[WARNING]   Required snappy library could not be found.
[WARNING]   SNAPPY_LIBRARY=SNAPPY_LIBRARY-NOTFOUND, SNAPPY_INCLUDE_DIR=,
[WARNING]   CUSTOM_SNAPPY_INCLUDE_DIR=,
[WARNING]   CUSTOM_SNAPPY_PREFIX=/myApps/software/snappy/1.1.7-GCCcore-6.4.0,
[WARNING]   CUSTOM_SNAPPY_INCLUDE=
```
Further on, the build fails with the error:
``` bash
[ERROR] Failed to execute goal org.apache.hadoop:hadoop-maven-plugins:2.9.2:cmake-compile (cmake-compile) on project hadoop-common: CMake failed with ee
rror code 1 -> [Help 1]
```

I have attached the debugging logs and the EB file.

Any idea what the error means? And how to fix this?

Regards,
Ehsan
[hadoop-logs.tar.gz](https://github.com/eth-cscs/production/files/3997802/hadoop-logs.tar.gz)

**Comment by gppezzi** [comment]
Hi @moravveji  

The error doesn't ring a bell.  How about opening the issue in the Official [EasyBuild Easyconfigs Github Repo](https://github.com/easybuilders/easybuild-easyconfigs/issues)?

**Comment by moravveji** [comment]
Thanks ... I did so.
https://github.com/easybuilders/easybuild-easyconfigs/issues/9619
