### ISSUE TITLE
EasyBuild for the installation of ANSYS Fluent

### ISSUE THREAD

**Issue by lisha992610** [eth-cscs/production#1658]
Hello, 

I am a new user of the Piz Daint. I was trying to use EasyBuild recipe to install Fluent 18.1 on the daint server for my simulation, which was not successful by directly using the recipe from easybuild. 

Another concern I have is, Daint has an OS of SUSE 15 and ANSYS is supported on Linux but not on SUSE 15. Is it still possible to install ANSYS on Piz Daint? I would appreciate for any advise how to install ANSYS on the CSCS cluster.   

Thank you very much.

**Comment by gppezzi** [comment]
Hello @lisha992610 ,

Could you please write to help@cscs.ch with this question, so that we can process your request through the official CSCS support channels.

Many thanks in advance.
G.
