### ISSUE TITLE
Update EB setup on kesch

### ISSUE THREAD

**Issue by gppezzi** [eth-cscs/production#222]
* [x] Implement a lowercase naming scheme (see https://github.com/eth-cscs/production/pull/221)
* Update variables PYTHONPATH and EASYBUILD_MODULE_NAMING_SCHEME for kesch
  * [x] in the EasyBuild-custom/cscs module
  * [x] in the respective .eb file

**Comment by lucamar** [comment]
This issue should now be closed, as we have the EB setup on Kesch.
