### ISSUE TITLE
spack: wrong variants for netcdf-fortran

### ISSUE THREAD

**Issue by albestro** [eth-cscs/production#2343]
@victorusu thank you for the work of updating spack configuration files!

I started using them when I realized that `netcdf-fortran` (I don't know about the others `netcdf-*`) does not have (anymore?) the variants specified, i.e. `mpi` and `parallel-netcdf`.

https://github.com/eth-cscs/production/blob/4f2e76b0b5623680caf4036f71769d6eb3e3d939/spack/daint/packages.yaml#L894-L899

**Comment by victorusu** [comment]
fixed by #2400

**Comment by albestro** [comment]
What am I missing? I see there are above the specs without, but I can see a lot of entries (quasi-duplicated) with the wrong variants.

I haven't opened a PR yet because I'm not really sure what's going on.

https://github.com/eth-cscs/production/blob/7dab3a901e43100cd6c15cf5d28e444d2f88efde/spack/daint/packages.yaml#L987-L1076
