### ISSUE TITLE
FTP download links not working on compute nodes

### ISSUE THREAD

**Issue by lucamar** [eth-cscs/production#275]
Issues downloading `netcdf-fortran`:
https://jenkins.cscs.ch/view/RegressionEB/job/RegressionEB/label=daint/20/consoleFull
```
Couldn't find file netcdf-fortran-4.4.4.tar.gz anywhere, and downloading it didn't work either
```

**Comment by lucamar** [comment]
I believe that the issue is the `ftp`download link that might not be allowed from the compute nodes of Piz Daint.

**Comment by jgphpc** [comment]
It is in
/apps/common/UES/easybuild/sources/n/netCDF-Fortran/netcdf-fortran-4.4.4.tar.gz

and also in
/users/jenscscs/sources/n/netCDF-Fortran/netcdf-fortran-4.4.4.tar.gz

=> ???

**Comment by lucamar** [comment]
The project `RegressionEB` starts the download from scratch to spot possible issues:  see my last comment in https://madra.cscs.ch/scs/doc/issues/143

**Comment by jgphpc** [comment]
The ftp command is not installed on dom:

piccinal@ela2:~$ rpm 
lukemftp-1.5-725.17

 piccinal@dom101:~$ 
which ftp
which: no ftp

**Comment by lucamar** [comment]
You don't need the command `ftp`to download from an `ftp`link, `wget`is enough on the login nodes, but not on the compute nodes, as the process hangs:
```
$ srun -C gpu --nodes=1 --pty /bin/bash -l
nid00000:~$ wget ftp://ftp.gromacs.org/pub/gromacs
--2017-08-25 16:23:19--  ftp://ftp.gromacs.org/pub/gromacs
           => ‘gromacs’
Resolving ftp.gromacs.org (ftp.gromacs.org)... 130.237.25.126, 2001:6b0:1:1190:5054:ff:fe2f:daed
Connecting to ftp.gromacs.org (ftp.gromacs.org)|130.237.25.126|:21...
```

**Comment by jgphpc** [comment]
right !

**Comment by lucamar** [comment]
The issue will be fixed by the network security team next week, so I will close it here
