### ISSUE TITLE
h5py serial crashes on an MPI init error

### ISSUE THREAD

**Issue by jfavre** [eth-cscs/production#376]
module load h5py/2.7.0-CrayGNU-17.08-python3-serial
python3
Python 3.5.2 (default, Jun 20 2017, 23:55:57) 
[GCC 6.1.0 20160427 (Cray Inc.)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
[Wed Sep 20 16:59:12 2017] [unknown] Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(537): 
MPID_Init(247).......: channel initialization failed
MPID_Init(636).......:  PMI2 init failed: 1 
Aborted (core dumped)

**Comment by jfavre** [comment]
the call to MPI is presumably the result of the configuration with the --mpi flag

this appears no different that the h5py-2.7.0-CrayGNU-17.08-python3-parallel.eb file besides the point that it uses the underlying parallel HDF5 lib.

Should --mpi be removed from the "serial" recipe?

**Comment by jgphpc** [comment]
see https://github.com/eth-cscs/production/pull/380 for a fix to h5py-2.7.0-CrayGNU-17.08-python3-serial.eb

**Comment by victorusu** [comment]
@jfavre, can we close this issue?
