### ISSUE TITLE
Incorrect default  version of TensorFlow

### ISSUE THREAD

**Issue by rsarm** [eth-cscs/production#625]
On the production list, `TensorFlow-1.3.0` is set to be the default:
```
TensorFlow-1.3.0-CrayGNU-17.08-cuda-8.0-python3.eb --set-default-module
```
However, the result of `module av TensorFlow` on Daint is:
```
TensorFlow/1.2.1-CrayGNU-17.08-cuda-8.0-python3(default)
....
```

**Comment by lucamar** [comment]
I've corrected the default version, but I still don't know why the production script did not set it properly.
