### ISSUE TITLE
multiple python modules loaded for ParaView

### ISSUE THREAD

**Issue by jfavre** [eth-cscs/production#642]
if using Boost to compile ParaView, Boost loads in the older Python module cray-python/17.06.1
and then the second module cray-python/3.6.1.1 is also loaded.

I feel like some of the run-time problems I see could be related (there is a lib/python3.5 folder), whereas ParaView probably looks for lib/python3.6

need to cleanup Boost.

**Comment by lucamar** [comment]
Fixed by #643
