### ISSUE TITLE
obsolete eglibs modules

### ISSUE THREAD

**Issue by jfavre** [eth-cscs/production#655]
directory /apps/daint/system/modulefiles/eglibs/ contains some obsolete modules which had very little purpose.

Should we ask ops to remove them completely?

Reference: https://webrt.cscs.ch/Ticket/Display.html?id=32246

**Comment by gppezzi** [comment]
I don't see why we should keep those, please go ahead and request the removal.

**Comment by jfavre** [comment]
ops has removed the moduleand files.
