### ISSUE TITLE
Score-P modules do not load correctly on Daint

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/production#898]
```
module load daint-gpu
module load Score-P/4.0-CrayIntel-18.08
```

```
libunwind(3):ERROR:105: Unable to locate a modulefile for 'libunwind/.1.2.1'
```

This causes ReFrame tests to fail.

**Comment by jgphpc** [comment]
> This causes ReFrame tests to fail

If this were really an `error` then the modulefile should not be loaded but it is (try `which scorep` for instance). A warning would make more sense here but I guess that's a feature of the module command.
Why `libunwind` is missing when it's declared as a dependency of Score-P is beyond my understanding.
I will reinstall it.

**Comment by jgphpc** [comment]
Solved.

```
jenscscs@daint106:~> module load daint-gpu
jenscscs@daint106:~> module load Score-P/4.0-CrayIntel-18.08
```
