### ISSUE TITLE
production_builds.sh for kesch

### ISSUE THREAD

**Issue by jgphpc** [eth-cscs/production#96]
Would it make sense to update the `production_builds.sh` for kesch ?

**Comment by lucamar** [comment]
I think it makes sense of course, but we need to adopt a uniform naming scheme for the lists of build on the different systems. In fact currently we have `6.0.UP02-2016.11-mc` (or -gpu) for Piz Daint,  `MCH-RH6.7-15.11` for Escha/Kesch, `common-SLES12-2016.10` for /apps/common, etc...

**Comment by gppezzi** [comment]
IMO that is fine, my only suggestions would be:
  * to use the same order as the path on the FS and start by system name
  * add (optional) partition as last argument

Something like:
  * ${system name under /apps}-${OS}-${PE}-{$PARTITION}

**Comment by lucamar** [comment]
${PARTITION}=[gpu,mc]?

**Comment by jgphpc** [comment]
gpu because kesch is haswell+gpu(s) ?

**Comment by lucamar** [comment]
No, I think that ${PARTITION} only currently applies to Piz Daint only, where we have different node types.

**Comment by lucamar** [comment]
Proposal: let's use symbolic links with system names that point to the correct production list file. E.g.:
`daint-mc -> 6.0.UP02-2016.11-mc`
The production script will then look for the system name (and architecture on Piz Daint only)
